// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dglufhvlbomdqadtthvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnbHVmaHZsYm9tZHFhZHR0aHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzOTUwNTMsImV4cCI6MjA1NDk3MTA1M30.oBTsHENAXMthJC0QQbPmD8Kdwp1RzCr9bIIDPV68_d0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);